/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleconnection;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static oracleconnection.Agent.conn;

/**
 *
 * @author RENU
 */
public class Pol_holder extends javax.swing.JFrame {

    /**
     * Creates new form Pol_holder
     */
    public Pol_holder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h_mob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ch_hkey = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        h_occ = new javax.swing.JTextField();
        h_dob = new javax.swing.JTextField();
        h_gen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        h_key = new javax.swing.JTextField();
        h_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        h_add = new javax.swing.JTextField();
        choose = new javax.swing.JComboBox<>();
        h_qual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        h_mob.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Holder_key");

        ch_hkey.setEnabled(false);
        ch_hkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_hkeyActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Choose Holder_key");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Holder_name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Holder_address");

        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("POLICY_HOLDER");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Holder_mobile");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Holder_occ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("DOB");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Gender");

        h_occ.setEnabled(false);
        h_occ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h_occActionPerformed(evt);
            }
        });

        h_dob.setEnabled(false);

        h_gen.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Holder_qual");

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        h_key.setAlignmentX(60.0F);
        h_key.setEnabled(false);
        h_key.setName(""); // NOI18N
        h_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h_keyActionPerformed(evt);
            }
        });

        h_name.setEnabled(false);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Holder_key", "Holder_name", "Holder_address", "Holder_qual", "Holder_mobile", "Holder_occ", "DOB", "Gender"
            }
        ));
        jScrollPane1.setViewportView(tab);

        h_add.setEnabled(false);

        choose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insert", "Update", "Delete" }));
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });

        h_qual.setEnabled(false);

        jLabel2.setText("Choose:");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(choose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(452, 452, 452))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h_key, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ch_hkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_name, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_add, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_qual, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_mob, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_occ, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(insert)
                        .addGap(32, 32, 32)
                        .addComponent(update)
                        .addGap(26, 26, 26)
                        .addComponent(delete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch_hkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(h_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(h_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(h_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(h_qual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h_mob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h_occ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert)
                    .addComponent(update)
                    .addComponent(delete))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String hname,add,qual,occ,gen,dob;
        int key;
        long mob;
        
        try
        {
            String driverName= "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "DESKTOP-H547RQN";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@"+serverName+":"+serverPort+":"+sid;
            String username = "Juhi_XE";
            String password = "oracle";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("System successfully connected to database");
            
        }
        catch(ClassNotFoundException e)
                {
                    System.out.println("Error 1");
                }
        catch(SQLException e)
                {
                    System.out.println("Error 2");
                }
                
                key=Integer.parseInt(h_key.getText());
                hname=h_name.getText();
                add=h_add.getText();
                gen=h_gen.getText();
                dob=h_dob.getText();
                qual=h_qual.getText();
                occ=h_occ.getText();
                mob=Long.parseLong(h_mob.getText());
                int selected=Integer.parseInt(ch_hkey.getSelectedItem().toString());
                try
                {
                    Statement st = conn.createStatement();
                    String str="Update policy_holder set holder_key="+key+",holder_name='"+hname+"',holder_address='"+add+"',gender='"+gen+"',holder_qual='"+qual+"',dob='"+dob+"',holder_occ='"+occ+"',holder_mobile="+mob+" where holder_key="+selected+"";
                    st.executeUpdate(str);
                    System.out.println(str);
                    st.close();
                    JOptionPane.showMessageDialog(null,"Updated!","Successful",JOptionPane.PLAIN_MESSAGE);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                dis();
                clear();
     
    }//GEN-LAST:event_updateActionPerformed

    private void h_occActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h_occActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h_occActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String hname,add,qual,occ,gen,dob;
        int key;
        long mob;
        
        try
        {
            String driverName= "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "DESKTOP-H547RQN";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@"+serverName+":"+serverPort+":"+sid;
            String username = "Juhi_XE";
            String password = "oracle";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("System successfully connected to database");
            
        }
        catch(ClassNotFoundException e)
                {
                    System.out.println("Error 1");
                }
        catch(SQLException e)
                {
                    System.out.println("Error 2");
                }
                
                 int selected=Integer.parseInt(ch_hkey.getSelectedItem().toString());
                try
                {
                    Statement st = conn.createStatement();
                    st.executeUpdate("delete from policy_holder where holder_key="+selected+"");
                    st.close();
                    JOptionPane.showMessageDialog(null,"Deleted!","Successful",JOptionPane.PLAIN_MESSAGE);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                dis();
                clear();
    }//GEN-LAST:event_deleteActionPerformed

    private void h_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h_keyActionPerformed

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
        String hname,add,qual,occ,gen,dob;
        int key;
        long mob;
        DefaultTableModel d2= (DefaultTableModel)tab.getModel();
            
        try
        {
            String driverName= "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "DESKTOP-H547RQN";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@"+serverName+":"+serverPort+":"+sid;
            String username = "Juhi_XE";
            String password = "oracle";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("System successfully connected to database");
            
        }
        catch(ClassNotFoundException e)
                {
                    System.out.println("Error 1");
                }
        catch(SQLException e)
                {
                    System.out.println("Error 2");
                }
        switch(choose.getSelectedIndex())
        {
            case 0: 
                en();
                clear();
                insert.setEnabled(true);
                update.setEnabled(false);
                delete.setEnabled(false);
                ch_hkey.setEnabled(false);
                ch_hkey.removeAllItems();
                break;
            case 1: 
            case 2:
                ch_hkey.setEnabled(true);
                ch_hkey.removeAllItems();
                try
                {
                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery("Select holder_key from policy_holder");
                    int i=0;
                    while(rs.next())
                    {
                        ch_hkey.addItem(String.valueOf(rs.getInt(1)));
                         i++;
                    }
                    if(i<1)
                    {
                        JOptionPane.showMessageDialog(null,"No record found","ERROR",JOptionPane.ERROR_MESSAGE);
                    }
                    rs.close();
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                
                en();
                if(choose.getSelectedIndex()==1){
                    update.setEnabled(true);
                    delete.setEnabled(false);
                    insert.setEnabled(false);
                }
                else if(choose.getSelectedIndex()==2){
                    delete.setEnabled(true);
                insert.setEnabled(false);
                update.setEnabled(false);}
                break;
                           
        }
    }//GEN-LAST:event_chooseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Insert_form l=new Insert_form();
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
String hname,add,qual,occ,gen,dob;
        int key;
        long mob;
        DefaultTableModel d2= (DefaultTableModel)tab.getModel();
            d2.setRowCount(0);
            tab.setModel(d2);
        try
        {
            String driverName= "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "DESKTOP-H547RQN";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@"+serverName+":"+serverPort+":"+sid;
            String username = "Juhi_XE";
            String password = "oracle";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("System successfully connected to database");
            
        }
        catch(ClassNotFoundException e)
                {
                    System.out.println("Error 1");
                }
        catch(SQLException e)
                {
                    System.out.println("Error 2");
                }
        try
        {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from policy_holder");
            int i=0;
            while(rs.next())
            {
                  key = rs.getInt(1);
                hname =rs.getString(2);
                add =rs.getString(3);
                qual =rs.getString(4);
                mob =rs.getLong(5);
                occ =rs.getString(6);
                    dob = rs.getString(7);
                    gen = rs.getString(8);
                d2.addRow(new Object[]{key,hname,add,qual,mob,occ,dob,gen});
                tab.setModel(d2);
                //System.out.println(hname);
                i++;
            }
            
            rs.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
                                    

    
                                          
            
    }//GEN-LAST:event_formWindowGainedFocus

    private void ch_hkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_hkeyActionPerformed
      try
        {
            String driverName= "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "DESKTOP-H547RQN";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@"+serverName+":"+serverPort+":"+sid;
            String username = "Juhi_XE";
            String password = "oracle";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("System successfully connected to database");
            
        }
        catch(ClassNotFoundException e)
                {
                    System.out.println("Error 1");
                }
        catch(SQLException e)
                {
                    System.out.println("Error 2");
                }
        
         if(ch_hkey.getItemCount()!=0)  { 
             int selected=Integer.parseInt(String.valueOf(ch_hkey.getSelectedItem()));
                System.out.println(selected);
        try
        {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from policy_holder where holder_key="+selected+"");
            int i=0;
            if(rs.next())
            {
                h_key.setText(String.valueOf(rs.getInt(1)));
                h_name.setText(rs.getString(2));
                h_add.setText(rs.getString(3));
                h_qual.setText(rs.getString(4));
                h_gen.setText(rs.getString(8));
                h_occ.setText(rs.getString(6));
                h_dob.setText(rs.getString(7));
                h_mob.setText(String.valueOf(rs.getLong(5)));
                i++;
            }
            if(i<1)
            {
                JOptionPane.showMessageDialog(null,"No record found","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            rs.close();
        }
            catch(Exception e)
            {
            e.printStackTrace();
        }
         }  
    }//GEN-LAST:event_ch_hkeyActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        String hname,add,qual,occ,gen,dob;
        int key;
        long mob;
        try
        {
            String driverName= "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "DESKTOP-H547RQN";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@"+serverName+":"+serverPort+":"+sid;
            String username = "Juhi_XE";
            String password = "oracle";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("System successfully connected to database");
            
        }
        catch(ClassNotFoundException e)
                {
                    System.out.println("Error 1");
                }
        catch(SQLException e)
                {
                    System.out.println("Error 2");
                }        
        key=Integer.parseInt(h_key.getText());
                hname=h_name.getText();
                add=h_add.getText();
                gen=h_gen.getText();
                dob=h_dob.getText();
                qual=h_qual.getText();
                occ=h_occ.getText();
                mob=Long.parseLong(h_mob.getText());
                try
                {
                    Statement st = conn.createStatement();
                    st.executeUpdate("Insert into policy_holder values("+key+",'"+hname+"','"+add+"','"+qual+"',"+mob+",'"+occ+"','"+dob+"','"+gen+"')");
                    st.close();
                    JOptionPane.showMessageDialog(null,"Record Inserted!","Successful",JOptionPane.PLAIN_MESSAGE);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                dis();
                clear();
                                          

    
    }//GEN-LAST:event_insertActionPerformed
    
        public void en()
    {
        h_key.setEnabled(true);
                h_name.setEnabled(true);
                h_add.setEnabled(true);
                h_gen.setEnabled(true);
                h_dob.setEnabled(true);
                h_mob.setEnabled(true);
                h_qual.setEnabled(true);
                h_occ.setEnabled(true);

    }
    public void dis()
    {
                ch_hkey.setEnabled(false);
                h_key.setEnabled(false);
                h_name.setEnabled(false);
                h_add.setEnabled(false);
                h_dob.setEnabled(false);
                h_mob.setEnabled(false);
                h_qual.setEnabled(false);
                h_occ.setEnabled(false);
                h_gen.setEnabled(false);
                insert.setEnabled(false);
                update.setEnabled(false);
                delete.setEnabled(false);
    }
    public void clear()
    {
       h_key.setText("");
                h_name.setText("");
                h_add.setText("");
                h_gen.setText("");
                h_dob.setText("");
                h_mob.setText("");
                h_qual.setText("");
                h_occ.setText(""); 
                ch_hkey.removeAllItems();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pol_holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pol_holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pol_holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pol_holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pol_holder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ch_hkey;
    private javax.swing.JComboBox<String> choose;
    private javax.swing.JButton delete;
    private javax.swing.JTextField h_add;
    private javax.swing.JTextField h_dob;
    private javax.swing.JTextField h_gen;
    private javax.swing.JTextField h_key;
    private javax.swing.JTextField h_mob;
    private javax.swing.JTextField h_name;
    private javax.swing.JTextField h_occ;
    private javax.swing.JTextField h_qual;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
